### ISSUE TITLE
Got Permission Denied Error While DDL

### ISSUE THREAD

**Issue by IronRobot** [ebean-orm/ebean-test-containers#113]
Configuration like this:
```
ebean:
  test:
    ddl:
      initSql: prepare.sql
    platform: mysql 
    ddlMode: dropCreate 
    dbName: test
```

Entity classes with different schemas:

```
 @Entity
@Table(name = "AdIndustry", schema = "DB_Customer_")
public class AdIndustryRecord {
...
}

@Entity
@Table(name = "CertificationApproved_", schema = "Customer_")
public class CertificationApprovedRecord {
...
}
```

I always got a permission denied error, like 
```
Error executing [create table DB_Customer_.AdIndustry (
...


CREATE command denied to user 'test'@'192.168.65.1' for table 'AdIndustry'
```
